version: "3"

services:
  postgresdb:
    image: postgres
    container_name: development-postgresdb
    # restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      # - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - postgresdatap:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: development-rabbitmq
    ports:
      - "15672:15672" # Management UI
      - "5672:5672"   # AMQP port
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend-net
    # restart: unless-stopped


  backend:
    build: .
    container_name: development
    ports:
      - "8030:8080"
    environment:
      - SPRING_CONFIG_LOCATION=/app/config/application.properties
      - spring.datasource.url=jdbc:postgresql://postgresdb:5432/admindb
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    volumes:
      - ./src/main/resources/application.properties:/app/config/application.properties
    networks:
      - backend-net
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgresdb:
        condition: service_healthy
    restart: unless-stopped

networks:
  backend-net:
    driver: bridge

volumes:
    postgresdatap: