name: Staging Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - staging

jobs:
  build-and-push:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    environment:
      name: "staging"
      url: ${{ vars.URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create application-staging.properties
        run: |
          echo "spring.profiles.active=staging" > src/main/resources/application.properties
          echo "${{ secrets.APPLICATION_PROPERTIES }}" | base64 --decode > src/main/resources/application-staging.properties

      - name: Add SSH Key to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: SSH into Server and Execute Command
        run: |
          sshpass -p ${{ secrets.STAGING_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.STAGING_USERNAME }}@${{ secrets.HOST }} "\
          cd ~/hng_boilerplate_java_web && \
          git fetch origin staging && \
          git stash && \
          git checkout staging && \
          git pull && \
          mvn clean install -Dmaven.test.skip=true && \
          sudo cp .github/scripts/java_staging_app.service /etc/systemd/system && \
          sudo systemctl daemon-reload && \
          sudo systemctl start java_staging_app.service && \
          exit"
