name: API Test and Status Update

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  run-newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection with HTML Reporter
        run: |
          newman run "hg_boilerplate_java_web/qa_tests/regression/Spartacus_Java_Boilerplate_copy-postman_collection.json" \
            --reporter htmlextra \
            --reporter-htmlextra-export "newman-report.html" \
            --reporter-json-export "result.json"

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Send parsed result to Hosted Application
        run: |
          export APP_URL=${{ secrets.APP_URL }}
          java -jar sendPostmanApiTestResults.jar newman-report.html result.json

      - name: Copy newman-report.html to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "newman-report.html"
          target: "/home/${{ secrets.USERNAME }}/hng_boilerplate_java_web"

