name: Staging-Deployment

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
    branches: [staging]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion=='success' && github.event.workflow_run.head_branch == 'staging' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compose Build Docker image
        run: docker compose -f docker-compose.staging.yml build
      
      - name: Save and compress Docker images
        run: |
          docker save $(docker-compose -f docker-compose.staging.yml config | grep 'image:' | awk '{print $2}') > staging-images.tar
          gzip staging-images.tar
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-images
          path: staging-images.tar.gz
      
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: docker-images
          path: .
      
      - name: Copy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.STAGING_SSH_USERNAME }}
          password: ${{ secrets.STAGING_SSH_PASSWORD }}
          source: "staging-images.tar.gz,docker-compose.staging.yml,.env,scripts/staging-deploy.sh"
          target: "~/tmp/hng_boilerplate_java_web"

      - name: Deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.STAGING_SSH_USERNAME }}
          password: ${{ secrets.STAGING_SSH_PASSWORD }}
          script: |
            cd ~/tmp/hng_boilerplate_java_web
            gunzip staging-images.tar.gz
            docker load < staging-images.tar
            rm -f staging-images.tar
            chmod +x ./scripts/staging-deploy.sh
            ./scripts/staging-deploy.sh 
      # - name: Add SSH Key to Known Hosts
      #   run: |
      #     mkdir -p ~/.ssh
      #     ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      #   env:
      #     SSH_HOST: ${{ secrets.SSH_HOST }}

      # - name: SSH into Server and Execute Command
      #   run: |
      #     sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST "\
      #     cd ~/hng_boilerplate_java_web && git fetch origin staging && git stash && git checkout staging && git pull && chmod +x deploy.sh && ./deploy.sh && sudo systemctl start java_staging_app.service && \
      #     exit"
      #   env:
      #     SSH_HOST: ${{ secrets.SSH_HOST }}
      #     SSH_USERNAME: ${{ secrets.STAGING_SSH_USERNAME }}
      #     SSH_PASSWORD: ${{ secrets.STAGING_SSH_PASSWORD }}

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion=='failure' }}
    steps:
      - run: echo "Triggering the Workflow Failed"
